### ISSUE TITLE
License violations and discussion regarding Modrinth plugin

### ISSUE THREAD

**Issue by triphora** [TeamGalacticraft/GalacticGradle#1]
Hi there @ROMVoid95,

I'm one of the authors of the [Modrinth Minotaur Gradle plugin](https://github.com/modrinth/minotaur). The LGPL-2.1 license has not been maintained in porting much of the code over from there to here. I'm going to ask that you please maintain the LGPL-2.1 license in any code derived directly from the Minotaur plugin.

Besides, why did you need to create a new version altogether anyway? You could have pull requested to the original repository -- if you want to discuss that you can feel free to join the [Modrinth Discord](https://discord.gg/EUHuJHt) and ping me (Emmaffle) in the #other channel.

**Comment by ROMVoid95** [comment]
Truthfully, I had originally used the Task class from Minotaur when the
modrinth task wasn't applying settings when supplied through the parent
publishing plugin, So i moved what I had to a local branch and ciped in the
classes as gradles error outputs were less than helpful when refreshing a
test project. Then after a work trip, I came back and just forgot what I
was doing and just worked with what was there. And this was a major
oversight. Anyway, our plugin is only supposed to configure most of the
settings automatically for our projects, and simply apply Minotaur and
configure it with our defaults. Which is what I have in that local branch
but I wouldn't be able to merge and push that branch until I get home. That
branch does not contain any classes from Minotaur. Sorry about the
confusion.

**Comment by triphora** [comment]
The said license issues have been resolved, thanks. I do still have to wonder why there's stuff you add to this but don't PR upstream (like the thing with the special dependencies DSL) -- but that's your decision, not mine.

**Comment by ROMVoid95** [comment]
> The said license issues have been resolved, thanks. I do still have to wonder why there's stuff you add to this but don't PR upstream (like the thing with the special dependencies DSL) -- but that's your decision, not mine.

Thanks! I was going to work on a PR as I did have some idea's that could be fruitful but wanted to refine things a bit. This project is my first production Gradle plugin so I wanted to get more in tune with this side of Gradle and have more confidence in coding plugins. But I'm working 12+ hour days for the next 2 weeks so my free time now is little. Feel free to contact me on discord @ ROM™#0950
